-- liquibase formatted sql

-- changeset konon:1749286017010-1
CREATE TABLE nodes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tree_id    BIGINT                                  NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    genre      CHAR,
    birth_date date,
    death_date date,
    comment    VARCHAR(255),
    photo_url  VARCHAR(255),
    CONSTRAINT pk_nodes PRIMARY KEY (id)
);

-- changeset konon:1749286017010-2
CREATE TABLE nodes_biography
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    node_id   BIGINT                                  NOT NULL,
    biography TEXT,
    CONSTRAINT pk_nodes_biography PRIMARY KEY (id)
);

-- changeset konon:1749286017010-3
CREATE TABLE parent_child_relations
(
    child_id  BIGINT,
    parent_id BIGINT NOT NULL,
    CONSTRAINT pk_parent_child_relations PRIMARY KEY (parent_id)
);

-- changeset konon:1749286017010-4
CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

-- changeset konon:1749286017010-5
CREATE TABLE trees
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    is_private BOOLEAN                                 NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_trees PRIMARY KEY (id)
);

-- changeset konon:1749286017010-6
CREATE TABLE user_role
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (role_id, user_id)
);

-- changeset konon:1749286017010-7
CREATE TABLE users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username       VARCHAR(255)                            NOT NULL,
    email          VARCHAR(255)                            NOT NULL,
    password_hash  VARCHAR(255)                            NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    photo          VARCHAR(255),
    email_verified BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset konon:1749286017010-8
CREATE TABLE verification_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255)                            NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    used        BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_verification_token PRIMARY KEY (id)
);

-- changeset konon:1749286017010-9
ALTER TABLE nodes_biography
    ADD CONSTRAINT uc_nodes_biography_node UNIQUE (node_id);

-- changeset konon:1749286017010-10
ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

-- changeset konon:1749286017010-11
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset konon:1749286017010-12
ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

-- changeset konon:1749286017010-13
ALTER TABLE verification_token
    ADD CONSTRAINT uc_verification_token_token UNIQUE (token);

-- changeset konon:1749286017010-14
ALTER TABLE nodes
    ADD CONSTRAINT FK_NODES_ON_TREE FOREIGN KEY (tree_id) REFERENCES trees (id);

-- changeset konon:1749286017010-15
ALTER TABLE verification_token
    ADD CONSTRAINT FK_VERIFICATION_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset konon:1749286017010-16
ALTER TABLE parent_child_relations
    ADD CONSTRAINT fk_parchirel_on_child FOREIGN KEY (child_id) REFERENCES nodes (id);

-- changeset konon:1749286017010-17
ALTER TABLE parent_child_relations
    ADD CONSTRAINT fk_parchirel_on_parent FOREIGN KEY (parent_id) REFERENCES nodes (id);

-- changeset konon:1749286017010-18
ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

-- changeset konon:1749286017010-19
ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_user FOREIGN KEY (user_id) REFERENCES users (id);

