-- liquibase formatted sql

-- changeset konon:1749286017011-1
CREATE TABLE node_photos (
                             id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                             node_id    BIGINT NOT NULL,
                             photo_url  VARCHAR(255) NOT NULL,
                             description VARCHAR(255),
                             CONSTRAINT pk_node_photos PRIMARY KEY (id)
);

-- changeset konon:1749286017011-2
ALTER TABLE node_photos
    ADD CONSTRAINT fk_node_photos_node FOREIGN KEY (node_id) REFERENCES nodes (id);