-- liquibase formatted sql

-- changeset konon:1749286017012-1
CREATE TABLE conversations (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               user1_id BIGINT NOT NULL,
                               user2_id BIGINT NOT NULL,
                               CONSTRAINT pk_conversations PRIMARY KEY (id)
);

-- changeset konon:1749286017012-2
ALTER TABLE conversations
    ADD CONSTRAINT uc_conversation_pair UNIQUE (user1_id, user2_id);

-- changeset konon:1749286017012-3
ALTER TABLE conversations
    ADD CONSTRAINT fk_conversations_user1 FOREIGN KEY (user1_id) REFERENCES users (id);

-- changeset konon:1749286017012-4
ALTER TABLE conversations
    ADD CONSTRAINT fk_conversations_user2 FOREIGN KEY (user2_id) REFERENCES users (id);

-- changeset konon:1749286017012-5
CREATE TABLE private_messages (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  conversation_id BIGINT NOT NULL,
                                  sender_id BIGINT NOT NULL,
                                  content VARCHAR(255) NOT NULL,
                                  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                  CONSTRAINT pk_private_messages PRIMARY KEY (id)
);

-- changeset konon:1749286017012-6
ALTER TABLE private_messages
    ADD CONSTRAINT fk_private_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id);

-- changeset konon:1749286017012-7
ALTER TABLE private_messages
    ADD CONSTRAINT fk_private_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id);