-- liquibase formatted sql

-- changeset konon:1749286017013-1
CREATE TABLE tree_subscriptions (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    tree_id BIGINT NOT NULL,
                                    user_id BIGINT NOT NULL,
                                    CONSTRAINT pk_tree_subscriptions PRIMARY KEY (id)
);

-- changeset konon:1749286017013-2
ALTER TABLE tree_subscriptions
    ADD CONSTRAINT uc_tree_subscriptions UNIQUE (tree_id, user_id);

-- changeset konon:1749286017013-3
ALTER TABLE tree_subscriptions
    ADD CONSTRAINT fk_tree_subscriptions_tree FOREIGN KEY (tree_id) REFERENCES trees (id);

-- changeset konon:1749286017013-4
ALTER TABLE tree_subscriptions
    ADD CONSTRAINT fk_tree_subscriptions_user FOREIGN KEY (user_id) REFERENCES users (id);